# Generated by Django 4.2.29 on 2026-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("homepage", "0001_initial"),
        ("homepage", "0002_clientlogo_url"),
        ("homepage", "0003_legalpage"),
        ("homepage", "0004_contactsubmission_cta_btn_primary_de_and_more"),
        ("homepage", "0005_sitesettings_de_fields"),
        ("homepage", "0006_remove_pricingtier_cta_label_de_and_more"),
        ("homepage", "0007_sitesettings_favicon_and_more"),
        ("homepage", "0008_delete_pricingtier_and_more"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HowItWorksStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(default="01", max_length=4)),
                ("title", models.CharField(max_length=100)),
                (
                    "title_de",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Title (DE)"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "description_de",
                    models.TextField(blank=True, verbose_name="Description (DE)"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "How It Works Step",
                "verbose_name_plural": "How It Works Steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("sports_club", "Sports Club / Team"),
                            ("retail_fashion", "Retail & Fashion Brand"),
                            ("corporate", "Corporate / Office"),
                            ("hospitality", "Hospitality / Uniforms"),
                            ("events", "Events / Promotions"),
                            ("ngo", "NGO / Non-profit"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("industry_other", models.CharField(blank=True, max_length=100)),
                ("contact_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner / Founder"),
                            ("buyer", "Buyer / Procurement"),
                            ("marketing", "Marketing / Brand Manager"),
                            ("manager", "Team / Club Manager"),
                            ("designer", "Designer"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True)),
                ("product_types", models.CharField(max_length=200)),
                ("product_other", models.CharField(blank=True, max_length=100)),
                ("num_styles", models.PositiveIntegerField(default=1)),
                (
                    "quantity_per_style",
                    models.CharField(
                        choices=[
                            ("50-100", "50–100 units"),
                            ("100-250", "100–250 units"),
                            ("250-500", "250–500 units"),
                            ("500-1000", "500–1,000 units"),
                            ("1000-5000", "1,000–5,000 units"),
                            ("5000+", "5,000+ units"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender_sizing",
                    models.CharField(
                        choices=[
                            ("unisex", "Unisex only"),
                            ("mens_womens", "Men's & Women's cuts"),
                            ("kids", "Kids / Youth sizes included"),
                            ("all", "All of the above"),
                        ],
                        max_length=30,
                    ),
                ),
                ("size_range", models.CharField(blank=True, max_length=100)),
                ("brand_colours", models.CharField(blank=True, max_length=200)),
                (
                    "print_method",
                    models.CharField(
                        choices=[
                            ("embroidery", "Embroidery"),
                            ("screen_print", "Screen Print"),
                            ("dtf", "DTF (Direct to Film)"),
                            ("dtg", "DTG (Direct to Garment)"),
                            ("sublimation", "Sublimation"),
                            ("heat_transfer", "Heat Transfer"),
                            ("unsure", "Not sure — advise me"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "print_positions",
                    models.CharField(
                        choices=[
                            ("1", "1 position"),
                            ("2", "2 positions"),
                            ("3-4", "3–4 positions"),
                            ("5+", "5+ positions"),
                            ("allover", "All-over print"),
                        ],
                        max_length=10,
                    ),
                ),
                ("has_logo", models.BooleanField(default=True)),
                (
                    "design_files_status",
                    models.CharField(
                        choices=[
                            ("yes_vector", "Yes — vector files ready (AI/EPS/SVG)"),
                            ("yes_raster", "Yes — raster files only (PNG/JPG)"),
                            ("no_need_design", "No — I need design help"),
                            ("no_brief_only", "No — I have a brief/concept only"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pantone_matching", models.BooleanField(default=False)),
                ("customisation_notes", models.TextField(blank=True)),
                (
                    "desired_delivery",
                    models.CharField(
                        choices=[
                            ("asap", "ASAP — as fast as possible"),
                            ("2-4weeks", "2–4 weeks"),
                            ("1-2months", "1–2 months"),
                            ("2-3months", "2–3 months"),
                            ("flexible", "Flexible — no hard deadline"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hard_deadline", models.DateField(blank=True, null=True)),
                (
                    "sample_required",
                    models.CharField(
                        choices=[
                            ("yes_required", "Yes — required before production"),
                            ("yes_preferred", "Yes — preferred but not required"),
                            ("no", "No — proceed straight to production"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_country",
                    models.CharField(default="Switzerland", max_length=100),
                ),
                ("delivery_city", models.CharField(blank=True, max_length=100)),
                ("split_delivery", models.BooleanField(default=False)),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_1k", "Under CHF 1,000"),
                            ("1k-5k", "CHF 1,000–5,000"),
                            ("5k-15k", "CHF 5,000–15,000"),
                            ("15k-50k", "CHF 15,000–50,000"),
                            ("50k+", "CHF 50,000+"),
                            ("undisclosed", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("budget_notes", models.CharField(blank=True, max_length=200)),
                (
                    "sustainability",
                    models.CharField(
                        choices=[
                            ("required", "Very important — required"),
                            ("preferred", "Preferred if possible"),
                            ("not_priority", "Not a priority"),
                        ],
                        default="not_priority",
                        max_length=20,
                    ),
                ),
                ("certifications_needed", models.CharField(blank=True, max_length=200)),
                ("existing_supplier", models.BooleanField(default=False)),
                (
                    "existing_supplier_notes",
                    models.CharField(blank=True, max_length=200),
                ),
                ("heard_about_us", models.CharField(blank=True, max_length=100)),
                ("additional_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Request",
                "verbose_name_plural": "Quote Requests",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "title_de",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Title (DE)"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "description_de",
                    models.TextField(blank=True, verbose_name="Description (DE)"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ClientLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="clients/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Client Logo",
                "verbose_name_plural": "Client Logos",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[("impressum", "Impressum"), ("agb", "AGB")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(help_text="Plain text or basic HTML")),
                ("last_updated", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal Page",
                "verbose_name_plural": "Legal Pages",
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone call"),
                            ("whatsapp", "WhatsApp"),
                            ("any", "Any — whatever is fastest"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("tshirts", "T-Shirts"),
                            ("polos", "Polo Shirts"),
                            ("hoodies", "Hoodies / Sweatshirts"),
                            ("jackets", "Jackets / Outerwear"),
                            ("sports_kits", "Sports Kits"),
                            ("workwear", "Workwear / Uniforms"),
                            ("caps", "Caps / Headwear"),
                            ("bags", "Bags / Accessories"),
                            ("mixed", "Mixed / Multiple"),
                            ("other", "Other / Not sure yet"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "order_size",
                    models.CharField(
                        choices=[
                            ("50-100", "50–100 units"),
                            ("100-250", "100–250 units"),
                            ("250-500", "250–500 units"),
                            ("500-1000", "500–1,000 units"),
                            ("1000+", "1,000+ units"),
                            ("unsure", "Not sure yet"),
                        ],
                        default="unsure",
                        max_length=20,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("asap", "ASAP"),
                            ("1month", "Within 1 month"),
                            ("1-3months", "1–3 months"),
                            ("flexible", "Flexible"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                (
                    "design_help",
                    models.CharField(
                        choices=[
                            ("have_files", "Yes — I have ready design files"),
                            ("need_help", "No — I need design/concept help too"),
                            ("have_concept", "I have a concept but need it refined"),
                        ],
                        default="have_files",
                        max_length=20,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("first_time", "First time ordering custom clothing"),
                            ("some", "Done it before, looking for a better supplier"),
                            ("experienced", "Experienced — know exactly what I need"),
                        ],
                        default="first_time",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(default="B2B Textile Solutions", max_length=100),
                ),
                (
                    "hero_headline_line1",
                    models.CharField(default="Clothing", max_length=100),
                ),
                (
                    "hero_headline_line2",
                    models.CharField(default="Built for", max_length=100),
                ),
                (
                    "hero_headline_line3",
                    models.CharField(default="Business.", max_length=100),
                ),
                (
                    "hero_subtext",
                    models.TextField(
                        default="From sports kits to retail lines — G2G Textiles delivers premium custom clothing at scale. No compromises, no middlemen."
                    ),
                ),
                (
                    "hero_cta_primary",
                    models.CharField(default="Get a Quote", max_length=60),
                ),
                (
                    "hero_cta_secondary",
                    models.CharField(default="See How It Works", max_length=60),
                ),
                ("hero_badge_year", models.CharField(default="2015", max_length=10)),
                (
                    "hero_badge_text",
                    models.CharField(default="Trusted by 300+ brands", max_length=60),
                ),
                (
                    "cta_label",
                    models.CharField(default="Ready to order?", max_length=60),
                ),
                (
                    "cta_headline_line1",
                    models.CharField(default="Let's build", max_length=100),
                ),
                (
                    "cta_headline_line2",
                    models.CharField(default="your order.", max_length=100),
                ),
                (
                    "cta_subtext",
                    models.TextField(
                        default="Get in touch directly or use the full quote wizard — it takes 5 minutes and gives us everything we need to send you a precise quote."
                    ),
                ),
                (
                    "cta_btn_primary",
                    models.CharField(default="Start Quote Wizard", max_length=60),
                ),
                (
                    "cta_btn_secondary",
                    models.CharField(default="Quick Contact", max_length=60),
                ),
                (
                    "footer_instagram_url",
                    models.URLField(
                        blank=True, default="https://instagram.com/g2gtextiles"
                    ),
                ),
                (
                    "footer_instagram_handle",
                    models.CharField(blank=True, default="@g2gtextiles", max_length=60),
                ),
                (
                    "footer_copyright",
                    models.CharField(default="© 2025 G2G Textiles.", max_length=100),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="meta/"),
                ),
                (
                    "meta_description_de",
                    models.TextField(
                        blank=True,
                        default="Hochwertige Individualkleidung für Unternehmen, Vereine und Marken. Ab 50 Stück. Kostenlose Beratung inklusive.",
                        max_length=160,
                    ),
                ),
                (
                    "meta_description_en",
                    models.TextField(
                        blank=True,
                        default="Premium custom clothing for businesses, sports clubs and brands. From 50 units. Free consulting included.",
                        max_length=160,
                    ),
                ),
                (
                    "meta_og_image",
                    models.ImageField(blank=True, null=True, upload_to="meta/"),
                ),
                (
                    "meta_title_de",
                    models.CharField(
                        blank=True,
                        default="G2G Textiles — B2B Textilien",
                        max_length=60,
                    ),
                ),
                (
                    "meta_title_en",
                    models.CharField(
                        blank=True,
                        default="G2G Textiles — B2B Custom Clothing",
                        max_length=60,
                    ),
                ),
                ("cta_btn_primary_de", models.CharField(blank=True, max_length=60)),
                ("cta_btn_secondary_de", models.CharField(blank=True, max_length=60)),
                ("cta_headline_line1_de", models.CharField(blank=True, max_length=100)),
                ("cta_headline_line2_de", models.CharField(blank=True, max_length=100)),
                ("cta_label_de", models.CharField(blank=True, max_length=60)),
                ("cta_subtext_de", models.TextField(blank=True)),
                ("hero_badge_text_de", models.CharField(blank=True, max_length=60)),
                ("hero_cta_primary_de", models.CharField(blank=True, max_length=60)),
                ("hero_cta_secondary_de", models.CharField(blank=True, max_length=60)),
                ("hero_eyebrow_de", models.CharField(blank=True, max_length=100)),
                (
                    "hero_headline_line1_de",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "hero_headline_line2_de",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "hero_headline_line3_de",
                    models.CharField(blank=True, max_length=100),
                ),
                ("hero_subtext_de", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
