# Generated by Django 4.2.29 on 2026-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientlogo",
            name="url",
            field=models.URLField(
                blank=True, help_text="Link to client website (optional)"
            ),
        ),
    ]
