# Generated by Django 4.2.29 on 2026-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_clientlogo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[("impressum", "Impressum"), ("agb", "AGB")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(help_text="Plain text or basic HTML")),
                ("last_updated", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal Page",
                "verbose_name_plural": "Legal Pages",
            },
        ),
    ]
