# Generated by Django 4.2.29 on 2026-03-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_sitesettings_de_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingtier",
            name="cta_label_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_btn_primary_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_btn_secondary_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_headline_line1_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_headline_line2_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_label_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_subtext_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_badge_text_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_cta_primary_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_cta_secondary_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_eyebrow_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_headline_line1_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_headline_line2_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_headline_line3_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_subtext_de",
        ),
    ]
