# Generated by Django 4.2.29 on 2026-03-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_remove_pricingtier_cta_label_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text=".ico or .png, 32x32px recommended",
                null=True,
                upload_to="meta/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_description_de",
            field=models.TextField(
                blank=True,
                default="Hochwertige Individualkleidung für Unternehmen, Vereine und Marken. Ab 50 Stück. Kostenlose Beratung inklusive.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_description_en",
            field=models.TextField(
                blank=True,
                default="Premium custom clothing for businesses, sports clubs and brands. From 50 units. Free consulting included.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_og_image",
            field=models.ImageField(
                blank=True,
                help_text="Social share image (1200x630px recommended)",
                null=True,
                upload_to="meta/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_title_de",
            field=models.CharField(
                blank=True, default="G2G Textiles — B2B Textilien", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_title_en",
            field=models.CharField(
                blank=True, default="G2G Textiles — B2B Custom Clothing", max_length=60
            ),
        ),
    ]
