# Generated by Django 4.2.29 on 2026-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_sitesettings_favicon_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PricingTier",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="cta_btn_primary_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="cta_btn_secondary_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="cta_headline_line1_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="cta_headline_line2_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="cta_label_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="cta_subtext_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="hero_badge_text_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="hero_cta_primary_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="hero_cta_secondary_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="hero_eyebrow_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="hero_headline_line1_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="hero_headline_line2_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="hero_headline_line3_de",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="hero_subtext_de",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_btn_primary_de",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_btn_secondary_de",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_headline_line1_de",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_headline_line2_de",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_label_de",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_subtext_de",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_text_de",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_cta_primary_de",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_cta_secondary_de",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_eyebrow_de",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_headline_line1_de",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_headline_line2_de",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_headline_line3_de",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtext_de",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="clientlogo",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="meta/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_og_image",
            field=models.ImageField(blank=True, null=True, upload_to="meta/"),
        ),
    ]
