# Generated by Django 4.2.29 on 2026-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial_squashed_0008_delete_pricingtier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="MP4 video for hero background (recommended: 1920x1080, compressed)",
                null=True,
                upload_to="hero/",
            ),
        ),
    ]
