# Generated by Django 4.2.29 on 2026-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_sitesettings_hero_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="MP4 or WebM video for hero background",
                null=True,
                upload_to="hero/",
            ),
        ),
    ]
