# Generated by Django 4.2.29 on 2026-04-01 14:57

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_alter_sitesettings_hero_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("name_de", models.CharField(blank=True, max_length=60)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="MP4 or WebM video for hero background",
                null=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="hero/",
            ),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_de", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("article", "Article / Guide"),
                            ("case_study", "Case Study"),
                            ("video", "Video Post"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary shown on listing page",
                        max_length=300,
                    ),
                ),
                ("excerpt_de", models.TextField(blank=True, max_length=300)),
                (
                    "body",
                    models.TextField(
                        help_text="HTML content — use &lt;h2&gt;, &lt;p&gt;, &lt;ul&gt;, &lt;strong&gt;, &lt;a&gt; etc."
                    ),
                ),
                ("body_de", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube or Vimeo embed URL e.g. https://www.youtube.com/embed/xxxxx",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="homepage.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_at"],
            },
        ),
    ]
