# Generated by Django 4.2.29 on 2026-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0011_blogcategory_alter_sitesettings_hero_video_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="SEO description (max 160 chars). Falls back to excerpt if empty.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO title (max 60 chars). Falls back to post title if empty.",
                max_length=60,
            ),
        ),
    ]
