# Generated by Django 4.2.29 on 2026-04-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_blogpostimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostimage",
            name="caption_de",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Caption (DE)"
            ),
        ),
    ]
