# Generated by Django 4.2.29 on 2026-04-18 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0014_blogpostimage_caption_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='assigned_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('quote_received', 'Quote Received'), ('in_review', 'In Review'), ('quote_sent', 'Quote Sent'), ('sampling', 'Sampling'), ('sample_approved', 'Sample Approved'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='status_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates_created', to=settings.AUTH_USER_MODEL)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='homepage.quoterequest')),
            ],
            options={
                'verbose_name': 'Order Status Update',
                'verbose_name_plural': 'Order Status Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
