# Generated by Django 4.2.29 on 2026-04-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_quoterequest_assigned_factory_quoterequest_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='notify_on_updates',
            field=models.BooleanField(default=True, help_text='Send the customer an email when a new status update is posted.'),
        ),
    ]
