# Generated by Django 4.2.29 on 2026-04-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_quoterequest_notify_on_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatusupdate',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderstatusupdate',
            name='tracking_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='orderstatusupdate',
            name='update_type',
            field=models.CharField(choices=[('update', 'Status Update'), ('issue', 'Delay / Issue')], default='update', max_length=10),
        ),
    ]
