# Generated by Django 4.2.29 on 2026-04-19 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0017_orderstatusupdate_tracking_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('currency', models.CharField(default='CHF', max_length=5)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('notes_internal', models.TextField(blank=True, help_text='Visible to staff only — not shown to the customer.')),
                ('notes_customer', models.TextField(blank=True, help_text='Shown on the customer-facing quote.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
                ('quote_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='homepage.quoterequest')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0–100)', max_digits=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='homepage.quote')),
            ],
            options={
                'verbose_name': 'Quote Line Item',
                'verbose_name_plural': 'Quote Line Items',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
