# Generated by Django 4.2.29 on 2026-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_quote_quotelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text='Mark once the customer has paid. The factory only sees this order after payment is confirmed.'),
        ),
    ]
