# Generated by Django 4.2.29 on 2026-04-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_payment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tech_pack_template',
            field=models.FileField(blank=True, help_text='Standard tech pack template PDF sent with proforma invoices. Same file used for all orders.', null=True, upload_to='documents/'),
        ),
    ]
