# Generated by Django 4.2.29 on 2026-04-21 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0020_tech_pack_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_role', models.CharField(choices=[('customer', 'Customer'), ('g2g_staff', 'G2G Staff')], max_length=20)),
                ('signature_image', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='homepage.quote')),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote Signature',
                'verbose_name_plural': 'Quote Signatures',
                'ordering': ['signed_at'],
                'unique_together': {('quote', 'signer_role')},
            },
        ),
    ]
